---
name: "Release"

on:
  push:
    branches: [master, dev]
    tags: ["v*"]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Try running mirror action"
        uses: ./
        with:
          REMOTE: git@gitgud.io:${{ github.repository }}.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.SYNC_PRIVATE_KEY }}
          GIT_PUSH_ARGS: --force --prune
          GIT_SSH_NO_VERIFY_HOST: true
          PUSH_ALL_REFS: false
          DEBUG: "true"
          DRY_RUN: "true"

      - name: "Build Changelog"
        if: startsWith(github.ref, 'refs/tags/')
        uses: mikepenz/release-changelog-builder-action@v6
        id: changelog
        with:
          configuration: ".github/configuration.json"
          mode: "HYBRID"

      - name: "Upload release"
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          body: ${{ steps.changelog.outputs.changelog }}

      - name: "Extract Major Version"
        if: startsWith(github.ref, 'refs/tags/')
        id: extract-version
        shell: bash
        run: |
          set -eEuxo pipefail
          echo "TAG_NAME=${GITHUB_REF_NAME%.*.*}" >> "$GITHUB_OUTPUT"

      - name: "Sync Major Tag"
        if: startsWith(github.ref, 'refs/tags/')
        uses: richardsimko/update-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract-version.outputs.TAG_NAME }}
